name: Windows
on:
  workflow_dispatch:
  push:
    paths:
      - QtScrcpy/**
      - "!QtScrcpy/res/**"
      - .github/workflows/windows.yml
      - ci/win**
  pull_request:
    paths:
      - QtScrcpy/**
      - "!QtScrcpy/res/**"
      - .github/workflows/windows.yml
      - ci/win**

jobs:
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      matrix:
        qt-ver: [5.15.2]
        qt-arch: [win64_msvc2019_64, win32_msvc2019]
        include:
          - qt-arch: win64_msvc2019_64
            msvc-arch: x64
            qt-arch-install: msvc2019_64
          - qt-arch: win32_msvc2019
            msvc-arch: x86
            qt-arch-install: msvc2019

    env:
      target-name: QtScrcpy
      vcvarsall-path: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat"
      vcinstall-path: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\Enterprise\\VC"
      qt-install-path: ${{{{ github.workspace }}}}/${{{{ matrix.qt-ver }}}}
      plantform-des: win

    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: ${{{{ env.qt-install-path }}}}/${{{{ matrix.qt-arch-install }}}}
          key: ${{{{ runner.os }}}}/${{{{ matrix.qt-ver }}}}/${{{{ matrix.qt-arch }}}}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{{{ matrix.qt-ver }}}}
          target: desktop
          arch: ${{{{ matrix.qt-arch }}}}
          cached: ${{{{ steps.cache-qt.outputs.cache-hit }}}}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build MSVC
        shell: cmd
        env:
          ENV_VCVARSALL: ${{{{ env.vcvarsall-path }}}}
          ENV_QT_PATH: ${{{{ env.qt-install-path }}}}
        run: |
          call python ci\generate-version.py
          call "ci\win\build_for_win.bat" RelWithDebInfo ${{{{ matrix.msvc-arch }}}}

      - name: Get the version
        shell: bash
        id: get-version
        run: echo ::set-output name=version::${GITHUB_REF##*/}

      - name: Package
        id: package
        env:
          ENV_VCVARSALL: ${{{{ env.vcvarsall-path }}}}
          ENV_VCINSTALL: ${{{{ env.vcinstall-path }}}}
          ENV_QT_PATH: ${{{{ env.qt-install-path }}}}
          publish_name: ${{{{ env.target-name }}}}-${{{{ env.plantform-des }}}}-${{{{ matrix.msvc-arch }}}}-${{{{ steps.get-version.outputs.version }}}}
        run: |
          cmd.exe /c ci\win\publish_for_win.bat ${{{{ matrix.msvc-arch }}}} ..\build\${{{{ env.publish_name }}}}
          Compress-Archive -Path ci\build\${{{{ env.publish_name }}}} ci\build\${{{{ env.publish_name }}}}.zip
          echo "::set-output name=package-name::${{{{ env.publish_name }}}}"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{{{ steps.package.outputs.package-name }}}}.zip
          path: ci\build\${{{{ steps.package.outputs.package-name }}}}

      - name: Upload Release
        if: startsWith(github.ref, refs/tags/)
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{{{ secrets.GITHUB_TOKEN }}}}
          file: ci\build\${{{{ steps.package.outputs.package-name }}}}.zip
          asset_name: ${{{{ steps.package.outputs.package-name }}}}.zip
          tag: ${{{{ github.ref }}}}
          overwrite: true
